include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/.gradle/**
  errors:
    invalid_use_of_protected_member: error
    invalid_use_of_visible_for_testing_member: error

linter:
  rules:
    avoid_print: true
    directives_ordering: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_super_parameters: true
